### PR TITLE
Marcin Łoś, Środa 17:50

### PR DESCRIPTION
**Pull request by piotrek-szczygiel**
hello i fix your code (broken)

### CODE REVIEW

**Comment by kaszperro** [comment]
Hi, thanks for contributing to this project :)
Unfortunately, your code doesn't match our standards. Maybe next time.

**Comment by piotrek-szczygiel** [comment]
I also changed line feeds to \r\n so i could edit this file on my Windows XP machine.
Please reconsider merging this request.

**Comment by kaszperro** [comment]
Thank you for your commitment. 
We like having only one line of code while editing in notepad.exe though.

**Comment by jakubowiczish** [comment]
Kaszperro's code stinks

**Comment by piotrek-szczygiel** [comment]
# Understandable, _have a nice day_.

**Pull request closed without merging**
